package wadapi;

/**
 * @author Zom-B
 */
// Created 2011-08-01
public enum LumpType {
	/** Unassigned or unknown */
	UNASSIGNED,

	/** Marker that surrounds other lumps of a certain type */
	MARKER,
	/** Map marker (followed by one of the map lumps) */
	MAP,
	/** Surrounded by markers */
	FLAT,
	/** Surrounded by markers */
	PATCH,
	/** Surrounded by markers */
	SPRITE,
	/** Surrounded by markers */
	FONT,
	COLORMAPS,
	ACSLIBRARY,
	NEWTEXTURES,
	STRIFEVOICES,
	HIRES,
	VOXELS,

	/** Map lump, Mandatory */
	THINGS,
	/** Map lump, Mandatory */
	LINEDEFS,
	/** Map lump, Mandatory */
	SIDEDEFS,
	/** Map lump, Mandatory */
	VERTEXES,
	/** Map lump, Generated by node builders */
	SEGS,
	/** Map lump, Generated by node builders */
	SSECTORS,
	/** Map lump, Generated by node builders */
	NODES,
	/** Map lump, Mandatory */
	SECTORS,
	/** Map lump, Generated by node builders */
	REJECT,
	/** Map lump, Generated by node builders */
	BLOCKMAP,
	/** Map lump, Optional */
	SCRIPTS,
	/** Map lump, Generated by script compilers, */
	BEHAVIOR,

	PLAYPAL,
	PNAMES,
//	TEXTURES, // Does this exist?
	/** TEXTURE1/2 */
	TEXTUREX,
	TEXT;

	public static boolean isMapLump(LumpType lumpType) {
		return lumpType == THINGS ||
		       lumpType == LINEDEFS ||
		       lumpType == SIDEDEFS ||
		       lumpType == VERTEXES ||
		       lumpType == SEGS ||
		       lumpType == SSECTORS ||
		       lumpType == NODES ||
		       lumpType == SECTORS ||
		       lumpType == REJECT ||
		       lumpType == BLOCKMAP ||
		       lumpType == SCRIPTS ||
		       lumpType == BEHAVIOR;
	}
}
