package wadapi.structure;

/**
 * LineSeg, generated by splitting Linedefs using partition lines selected by BSP builder.
 *
 * @author Zom-B
 */
// Created 2011-08-15
public class Segment {
	private int     v1;
	private int     v2;
	private int     angle;
	private int     linedef;
	private boolean backSide;
	private int     offset;

	public Segment(int v1, int v2, int angle, int linedef, boolean backSide, int offset) {
		this.v1 = v1;
		this.v2 = v2;
		this.angle = angle;
		this.linedef = linedef;
		this.backSide = backSide;
		this.offset = offset;
	}

	public int getV1() {
		return v1;
	}

	public int getV2() {
		return v2;
	}

	public int getAngle() {
		return angle;
	}

	public int getLinedef() {
		return linedef;
	}

	public boolean isBackSide() {
		return backSide;
	}

	public int getOffset() {
		return offset;
	}

	@Override
	public String toString() {
		return "[" + v1 +
		       ", " + v2 +
		       ", a=" + angle / 32768.0f +
		       ", ld=" + linedef +
		       ", " + (backSide ? "back" : "front") +
		       ", o=" + offset +
		       ']';
	}
}
