package wadapi.structure;

/**
 * LineSeg, generated by splitting Linedefs using partition lines selected by BSP builder.
 *
 * @author Zom-B
 */
// Created 2011-08-15
public class Segment {
	private int     v1;
	private int     v2;
	private int     linedef;
	private boolean backSide;

	public Segment(int v1, int v2, int linedef, boolean backSide) {
		this.v1 = v1;
		this.v2 = v2;
		this.linedef = linedef;
		this.backSide = backSide;
	}

	public int getV1() {
		return v1;
	}

	public int getV2() {
		return v2;
	}

	public int getLinedef() {
		return linedef;
	}

	public boolean isBackSide() {
		return backSide;
	}

	@Override
	public String toString() {
		return "[" + v1 +
		       ", " + v2 +
		       ", ld=" + linedef +
		       ", " + (backSide ? "back" : "front") +
		       ']';
	}
}
